# Generated by Django 4.0.3 on 2022-03-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da chave')),
                ('numero', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Número da chave')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Ultimo Nome')),
                ('date_reservation', models.DateTimeField(auto_now_add=True, verbose_name='Data da Reserva')),
                ('date_devoltution', models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Devolução')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaApi.key')),
            ],
        ),
    ]
