# Generated by Django 4.0.3 on 2022-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='numero',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Número da chave'),
        ),
    ]
