# Generated by Django 4.0.3 on 2022-03-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaApi', '0003_alter_key_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date_reservation'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
