# Generated by Django 4.0.3 on 2022-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaApi', '0008_alter_reservation_date_devoltution'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation',
            field=models.BooleanField(default=False, verbose_name='Reservado?'),
        ),
    ]
