# Generated by Django 4.0.3 on 2022-03-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaApi', '0009_reservation_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation',
            field=models.BooleanField(default=True, verbose_name='Reservado?'),
        ),
    ]
