# Generated by Django 4.0.3 on 2022-03-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaApi', '0010_alter_reservation_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_devoltution',
            new_name='date_devolution',
        ),
    ]
